### ISSUE TITLE
Speed of cmd_vel and odom are not same

### ISSUE THREAD

**Issue by suguruhamada1003910** [ezWheelSAS/swd_ros_controllers#59]
I noticed that the value of `/swd_diff_drive_controller/cmd_vel/Twist/linear/x` and `/swd_diff_drive_controller/odom/twist/twist/linear/x` are not same.

In the following image, I think the values of two should be 0.5. What do you think?

![Screenshot from 2022-12-16 13-43-55](https://user-images.githubusercontent.com/101627039/208025172-67ca08d1-e202-45a2-9dd9-aa3b6b9df8e7.png)

I uploaded rosbag file in the following URL.
https://1drv.ms/u/s!AqHxzXmtIbtrqQE7FJaLBYZf8ZTM?e=gQIjQt

**Comment by suguruhamada1003910** [comment]
@ez-Support 

Thank you for reply. I could not understand your message.
You mean if "/swd_diff_drive_controller/cmd_vel/Twist/linear/x" is 0.5, "/swd_diff_drive_controller/odom/twist/twist/linear/x" can be 2.0 or greater.
Is my understanding correct?

**Comment by ez-Support** [comment]
Those two values does not reprensent the same thing.

`/swd_diff_drive_controller/odom/twist/twist/linear/x` reprepsents the distance travelled by the robot :

> odom.twist.twist.linear.x = d_dist_center * m_pub_freq_hz;

where `/swd_diff_drive_controller/cmd_vel/Twist/linear/x` represents the  speed demand in m/s of the robot

**Comment by abougouffa** [comment]
Hello @suguruhamada1003910,

I've checked the `swd_ros_controllers` code to see what can cause such an issue, but didn't find any mistake in the odometry/twist calculation routines.

In order to help us investigate this further, can you please:

- Check if the configuration files you are using (`*.ini` files for the left and the right motors) are adequate with the real robot parameters, specially the wheel diameters?
- As it seems, you are repeatedly executing a straight line movement of 1.5 m. Please check if the distance measured by the odometry (in `/swd_diff_drive_controller/odom/pose/pose/x`) is close to the ground truth (a.k.a. is robot is travelling around 1.5 m in reality or the odometry is also wrong?)

**Comment by suguruhamada1003910** [comment]
@abougouffa @ez-Support 

I tried to reproduce this problem again but I could not reproduce it...
Therefore, I close this.

Thank you for support always!!
